sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

before_install:
 - chmod +x gradlew

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    - docker build -t cake-manager-demo .
    - docker push ryanrush/cake.manager.demo:cake-manager-demo
  on:
    branch: master
