sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

before_install:
  - chmod +x gradlew
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  -  docker build -t ryanrush/cake-manager-api-docker-repo .

deploy:
  provider: script
  script:
    docker push ryanrush/cake-manager-api-docker-repo
  on:
    branch: master