sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

before_install:
 - chmod +x gradlew

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    - docker build -t ryan.rush/cake.manager.demo:cake-api-demo .
    - docker push ryan.rush/cake.manager.demo:cake-api-demo
  on:
    branch: master
