INSERT INTO cake VALUES
    (1,'Lemon cheesecake','A cheesecake made of lemon','https://s3-eu-west-1.amazonaws.com/s3.mediafileserver.co.uk/carnation/WebFiles/RecipeImages/lemoncheesecake_lg.jpg'),
    (2,'victoria sponge','sponge with jam','http://www.bbcgoodfood.com/sites/bbcgoodfood.com/files/recipe_images/recipe-image-legacy-id--1001468_10.jpg'),
    (3,'Carrot cake','Bugs bunnys favourite','http://www.villageinn.com/i/pies/profile/carrotcake_main1.jpg'),
    (4,'Banana cake','Donkey kongs favourite','http://ukcdn.ar-cdn.com/recipes/xlarge/ff22df7f-dbcd-4a09-81f7-9c1d8395d936.jpg'),
    (5,'Birthday cake','a yearly treat','http://cornandco.com/wp-content/uploads/2014/05/birthday-cake-popcorn.jpg'),
    (6,'Lemon cheesecake','A cheesecake made of lemon','https://s3-eu-west-1.amazonaws.com/s3.mediafileserver.co.uk/carnation/WebFiles/RecipeImages/lemoncheesecake_lg.jpg'),
    (7,'victoria sponge','sponge with jam','http://www.bbcgoodfood.com/sites/bbcgoodfood.com/files/recipe_images/recipe-image-legacy-id--1001468_10.jpg'),
    (8,'Carrot cake','Bugs bunnys favourite','http://www.villageinn.com/i/pies/profile/carrotcake_main1.jpg'),
    (9,'Banana cake','Donkey kongs favourite','http://ukcdn.ar-cdn.com/recipes/xlarge/ff22df7f-dbcd-4a09-81f7-9c1d8395d936.jpg'),
    (10,'Birthday cake','a yearly treat','http://cornandco.com/wp-content/uploads/2014/05/birthday-cake-popcorn.jpg'),
    (11,'Lemon cheesecake','A cheesecake made of lemon','https://s3-eu-west-1.amazonaws.com/s3.mediafileserver.co.uk/carnation/WebFiles/RecipeImages/lemoncheesecake_lg.jpg'),
    (12,'victoria sponge','sponge with jam','http://www.bbcgoodfood.com/sites/bbcgoodfood.com/files/recipe_images/recipe-image-legacy-id--1001468_10.jpg'),
    (13,'Carrot cake','Bugs bunnys favourite','http://www.villageinn.com/i/pies/profile/carrotcake_main1.jpg'),
    (14,'Banana cake','Donkey kongs favourite','http://ukcdn.ar-cdn.com/recipes/xlarge/ff22df7f-dbcd-4a09-81f7-9c1d8395d936.jpg'),
    (15,'Birthday cake','a yearly treat','http://cornandco.com/wp-content/uploads/2014/05/birthday-cake-popcorn.jpg'),
    (16,'Lemon cheesecake','A cheesecake made of lemon','https://s3-eu-west-1.amazonaws.com/s3.mediafileserver.co.uk/carnation/WebFiles/RecipeImages/lemoncheesecake_lg.jpg'),
    (17,'victoria sponge','sponge with jam','http://www.bbcgoodfood.com/sites/bbcgoodfood.com/files/recipe_images/recipe-image-legacy-id--1001468_10.jpg'),
    (18,'Carrot cake','Bugs bunnys favourite','http://www.villageinn.com/i/pies/profile/carrotcake_main1.jpg'),
    (19,'Banana cake','Donkey kongs favourite','http://ukcdn.ar-cdn.com/recipes/xlarge/ff22df7f-dbcd-4a09-81f7-9c1d8395d936.jpg'),
    (20,'Birthday cake','a yearly treat','http://cornandco.com/wp-content/uploads/2014/05/birthday-cake-popcorn.jpg');
